### ISSUE TITLE
How to create grid files in realistic bathymetry by stompy

### ISSUE THREAD

**Issue by WanChou** [rustychris/stompy#5]
Hi Rusty,

This is my first time to use stompy.

How to create grid files in realistic bathymetry by stompy

Sincerely,  
Chou

**Comment by rustychris** [comment]
Hi Chou -
  A good starting point is to run the script test/test_tom.sh

There is not a built-in way to directly build a grid from bathymetry.  Instead, it requires you to provide (a) a shoreline shapefile, and (b) a shapefile describing how the resolution varies over the domain.  There are ways to use the underlying python classes to do more sophisticated things, like adjusting the resolution of the grid based on the bathymetry, but you'll have the best luck starting with a simpler approach.

hope that helps --
Rusty

**Comment by WanChou** [comment]
Hi Rusty,

This is a great beginning of this case.

Thank you for your prompt reply.

Sincerely,
Chou
